{
 "title": "Container usage",
 "time": { "from": "2025-08-22T11:30:00.000Z", "to": "2025-08-24T12:15:00.000Z" },
 "templating": {
  "list": [
   { "name": "namespaces", "label": "Namespaces", "query": { "query": "label_values(namespace)" } },
   {
    "name": "nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"$namespaces\"},node)"
    }
   },
   {
    "name": "internalIp",
    "label": "Internal IP",
    "query": {
     "query": "label_values(kube_node_info{node=~\"$nodes\"},internal_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total CTF Pilot deployments",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_deployment_labels{namespace=~\"$namespaces\", label_ctfpilot_com_name!=\"\"})",
     "legendFormat": "Deployments"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespaces\", container!=\"\", image!=\"\", node=~\"$nodes\"}[$__rate_interval]))",
     "legendFormat": "Total vCPU usage"
    },
    {
     "expr": "sum(node:node_num_cpu:sum{node=~\"$nodes\"})",
     "legendFormat": "Total vCPU available"
    },
    {
     "expr": "sum(node:node_num_cpu:sum{node=~\"$nodes\"})\r\n/\r\ncount(count(node:node_num_cpu:sum{node=~\"$nodes\"}) by (node))\r\n",
     "legendFormat": "Node available vCPU"
    },
    { "expr": "sum(node:node_num_cpu:sum)", "legendFormat": "Cluster vCPU available" }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespaces\", container!=\"\", image!=\"\", instance=~\"$internalIp:10250\"})",
     "legendFormat": "Total memory usage"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$internalIp:9100\"})",
     "legendFormat": "Total available memory"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$internalIp:9100\"}) /\r\ncount(count(node_memory_MemTotal_bytes{instance=~\"$internalIp:9100\"}) by (instance))",
     "legendFormat": "Node available memory"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Cluster memory available"
    }
   ]
  },
  {
   "title": "Node",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node vCPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:node_num_cpu:sum{node=~\"$nodes\"}) / count(count(node:node_num_cpu:sum{node=~\"$nodes\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$internalIp:9100\"}) /\r\ncount(count(node_memory_MemTotal_bytes{instance=~\"$internalIp:9100\"}) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total vCPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:node_num_cpu:sum{node=~\"$nodes\"}) / count(count(node:node_num_cpu:sum{node=~\"$nodes\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$internalIp:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster node count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster vCPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node:node_num_cpu:sum)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}