{
 "title": "CTFd",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "brackets",
    "label": "Brackets",
    "query": {
     "query": "label_values(ctfd_team_score,bracket)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Core information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scoreboard",
   "type": "timeseries",
   "description": "Top 10 teams in brackets",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum by(name) (ctfd_team_score{bracket=~\"$brackets\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 15 teams",
   "type": "table",
   "gridPos": { "h": 17, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "topk(15, sum by(name) (last_over_time(ctfd_team_score[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most solves",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "topk(15, sum(ctfd_submission_solves) by(name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Least solved (> 0)",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "bottomk(\n  15,\n  sum(ctfd_challenge_solves) by(name) > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solves per category",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ctfd_challenge_solves) by (category)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsolved challenges",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 5, "y": 18 },
   "targets": [
    {
     "expr": "bottomk(\n  10,\n  sum(ctfd_challenge_solves) by(name, category) == 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most fails",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, sum(ctfd_submission_fails) by(name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ctfd_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total teams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ctfd_teams_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total challenges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ctfd_challenges_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active instances",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "count(kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scoreboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Top 20 teams for $brackets",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "repeat": "brackets",
   "targets": [
    {
     "expr": "topk(20, ctfd_team_score{bracket=\"$brackets\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Additional data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    { "expr": "ctfd_users_total", "legendFormat": "Users" },
    { "expr": "ctfd_teams_total", "legendFormat": "Teams" }
   ]
  }
 ]
}