{
 "title": "Challenges Dashboard",
 "tags": [
  "ctfpilot",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "Granularity", "query": "1m,5m,15m,1h" }
  ]
 },
 "panels": [
  { "title": "Running challenges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"})",
     "legendFormat": "Total Instances"
    }
   ]
  },
  {
   "title": "Instances by Challenge Name",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "count by (label_ctfpilot_com_name) (kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Instances by Challenge Type",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "count by (label_ctfpilot_com_type) (kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Instances by Challenge Owner",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "count by (label_instanced_challenges_ctfpilot_com_owner) (kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Instances by Deployment ID",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "count by (deployment) (kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_instanced_challenges_ctfpilot_com_deployment!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Enabled Challenges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_configmap_labels{namespace=\"challenge-config\", label_challenges_ctfpilot_com_name!=\"\", label_challenges_ctfpilot_com_enabled!=\"false\"})",
     "legendFormat": "Enabled Challenges"
    }
   ]
  },
  {
   "title": "Total Instances Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count(kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"})",
     "legendFormat": "Total Instances"
    },
    {
     "expr": "count(kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"}) by (label_ctfpilot_com_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances by Challenge Name Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "count by (label_ctfpilot_com_name) (kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"})",
     "legendFormat": "{{label_ctfpilot_com_name}}"
    }
   ]
  },
  {
   "title": "Instances by Owner Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "count by (label_instanced_challenges_ctfpilot_com_owner) (kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_instanced_challenges_ctfpilot_com_owner!=\"\"})",
     "legendFormat": "{{label_instanced_challenges_ctfpilot_com_owner}}"
    }
   ]
  },
  {
   "title": "Instances by Type Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "count by (label_ctfpilot_com_type) (kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_type!=\"\"})",
     "legendFormat": "{{label_ctfpilot_com_type}}"
    }
   ]
  },
  {
   "title": "Enabled Challenges by Type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "count by (label_challenges_ctfpilot_com_type) (kube_configmap_labels{namespace=\"challenge-config\", label_challenges_ctfpilot_com_name!=\"\", label_challenges_ctfpilot_com_enabled!=\"false\"})",
     "legendFormat": "{{label_challenges_ctfpilot_com_type}}"
    }
   ]
  },
  {
   "title": "CPU usage of instances",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=~\"ctfpilot-challenges|ctfpilot-challenges-instanced\"}[$__rate_interval]))",
     "legendFormat": "Total CPU"
    },
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{namespace=~\"ctfpilot-challenges|ctfpilot-challenges-instanced\"}[$__rate_interval]))",
     "legendFormat": "{{label_challenges_ctfpilot_com_type}}"
    }
   ]
  },
  {
   "title": "Memory usage of instances",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=~\"ctfpilot-challenges|ctfpilot-challenges-instanced\"}[$__rate_interval])) / 1000000000",
     "legendFormat": "Total CPU"
    },
    {
     "expr": "sum by(namespace) (rate(container_memory_usage_bytes{namespace=~\"ctfpilot-challenges|ctfpilot-challenges-instanced\"}[$__rate_interval])) / 1000000000",
     "legendFormat": "{{label_challenges_ctfpilot_com_type}}"
    }
   ]
  },
  {
   "title": "Enabled Challenges by Category",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (label_challenges_ctfpilot_com_category) (kube_configmap_labels{namespace=\"challenge-config\", label_challenges_ctfpilot_com_name!=\"\", label_challenges_ctfpilot_com_enabled!=\"false\"})",
     "legendFormat": "{{label_challenges_ctfpilot_com_type}}"
    }
   ]
  },
  {
   "title": "Challenges by Enabled",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (label_challenges_ctfpilot_com_enabled) (kube_configmap_labels{namespace=\"challenge-config\", label_challenges_ctfpilot_com_name!=\"\", label_challenges_ctfpilot_com_enabled!=\"false\"})",
     "legendFormat": "{{label_challenges_ctfpilot_com_type}}"
    }
   ]
  },
  {
   "title": "Instances deployed by name",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"}) by (label_ctfpilot_com_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances deployed by type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_labels{namespace=~\"ctfpilot-challenges-instanced|ctfpilot-challenges\", label_ctfpilot_com_name!=\"\"}) by (label_ctfpilot_com_type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}